# Generated by Django 5.1.2 on 2024-11-07 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoTennis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo_superficie', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='slotorario',
            name='campo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='gestione.campotennis'),
        ),
    ]
