# Generated by Django 5.1.2 on 2024-11-07 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0002_campotennis_slotorario_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campotennis',
            name='disponibile',
            field=models.BooleanField(default=True),
        ),
    ]
