# Generated by Django 5.1.2 on 2024-11-12 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0004_prenotazione'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenotazione',
            name='data',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
